import time 
import subprocess
import os 

def cat(delay):
	print("   /\\_____/\\	 _    _ _    _____ _                   _ 										")
	time.sleep(delay)
	print("  /  o   o  \\   | |  | (_)  / ____| |                 | |											")
	time.sleep(delay)
	print(" ( ==  ^  == )  | |__| |_  | (___ | |__   __ _ _ __   | |										")
	time.sleep(delay)
	print("  )         (   |  __  | |  \\___ \\| '_ \\ / _` | '_ \\  | |										")
	time.sleep(delay)
	print(" (           )  | |  | | |  ____) | | | | (_| | | | | |_|										")
	time.sleep(delay)
	print("( (  )   (  ) ) |_|  |_|_| |_____/|_| |_|\\__,_|_| |_| (_)									")
	time.sleep(delay)
	print()
	return

def will(delay):
	print("__          ___ _ _                       _                            ")
	time.sleep(delay)
	print("\\ \\        / (_) | |                     | |                           ")
	time.sleep(delay)
	print(" \\ \\  /\\  / / _| | |  _   _  ___  _   _  | |__   ___   _ __ ___  _   _ ")
	time.sleep(delay)
	print("  \\ \\/  \\/ / | | | | | | | |/ _ \\| | | | | '_ \\ / _ \\ | '_ ` _ \\| | | |   ")
	time.sleep(delay)
	print("   \\  /\\  /  | | | | | |_| | (_) | |_| | | |_) |  __/ | | | | | | |_| |  _   _   _")
	time.sleep(delay)
	print("    \\/  \\/   |_|_|_|  \\__, |\\___/ \\__,_| |_.__/ \\___| |_| |_| |_|\\__, | (_) (_) (_)   ")
	time.sleep(delay)
	print("                       __/ |                                      __/ |             ")	
	time.sleep(delay)
	print("                      |___/                                      |___/              ")

def banquet(delay):
	print(" ___                                                         ___             ___            ___                                ")
	time.sleep(delay)
	print("(   )                                                       (   )           (   )          (   )                   .---.       ")
	time.sleep(delay)
	print(" | |.-.     .---.   ___ .-.     .--.     ___  ___    .--.    | |_         .-.| |    .---.   | |_       .--.       /  _   \\")
	time.sleep(delay)
	print(" | /   \\   / .-, \\ (   )   \\   /    \\   (   )(   )  /    \\  (   __)      /   \\ |   / .-, \\ (   __)    /    \\     | |   `. . ")
	time.sleep(delay)
	print(" |  .-. | (__) ; |  |  .-. .  |  .-. '   | |  | |  |  .-. ;  | |        |  .-. |  (__) ; |  | |      |  .-. ;   (___)   | |")
	time.sleep(delay)
	print(" | |  | |   .'`  |  | |  | |  | |  | |   | |  | |  |  | | |  | | ___    | |  | |    .'`  |  | | ___  |  | | |        .-'_/")
	time.sleep(delay)
	print(" | |  | |  / .'| |  | |  | |  | |  | |   | |  | |  |  |/  |  | |(   )   | |  | |   / .'| |  | |(   ) |  |/  |        | |")
	time.sleep(delay)
	print(" | |  | | | /  | |  | |  | |  | |  | |   | |  | |  |  ' _.'  | | | |    | |  | |  | /  | |  | | | |  |  ' _.'        |_|")
	time.sleep(delay)
	print(" | '  | | ; |  ; |  | |  | |  | '  | |   | |  ; '  |  .'.-.  | ' | |    | '  | |  ; |  ; |  | ' | |  |  .'.-.")
	time.sleep(delay)
	print(" ' `-' ;  ' `-'  |  | |  | |  ' `-'  |   ' `-'  /  '  `-' /  ' `-' ;    ' `-'  /  ' `-'  |  ' `-' ;  '  `-' /        .-.")
	time.sleep(delay)
	print("  `.__.   `.__.'_. (___)(___)  `._ / |    '.__.'    `.__.'    `.__.      `.__,'   `.__.'_.   `.__.    `.__.'        (   )")
	time.sleep(delay)
	print("                                   | |                                                                               `-' ")
	time.sleep(delay)
	print("                                   |_|                                                                               `-'")

def fence(delay):
	print("                      /^--^\\     /^--^\\     /^--^\\")
	time.sleep(delay)
	print("                      \\____/     \\____/     \\____/")
	time.sleep(delay)
	print("                     /      \\   /      \\   /      \\")
	time.sleep(delay)
	print("                    |        | |        | |        |")
	time.sleep(delay)
	print("                     \\__  __/   \\__  __/   \\__  __/")
	time.sleep(delay)
	print("|^|^|^|^|^|^|^|^|^|^|^|^\\ \\^|^|^|^/ /^|^|^|^|^\\ \\^|^|^|^|^|^|^|^|^|^|^|^|")
	time.sleep(delay)
	print("| | | | | | | | | | | | |\\ \\| | |/ /| | | | | | \\ \\ | | | | | | | | | | |")
	time.sleep(delay)
	print("########################/ /######\\ \\###########/ /#######################")
	time.sleep(delay)
	print("| | | | | | | | | | | | \\/| | | | \\/| | | | | |\\/ | | | | | | | | | | | |")
	time.sleep(delay)
	print("|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|_|")

def main():
	cat(0.09)
	time.sleep(2)
	will(0.09)
	time.sleep(1)
	banquet(0.09)
	time.sleep(3)
	os.system("echo " "")
	fence(0.09)
	time.sleep(5)
	os.system("clear")
	os.system("neofetch --ascii_distro mac")
main()